[package]
name = "nvim-traveller-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
#neo-api-rs = { git = "https://github.com/norlock/neo-api-rs" }
neo-api-rs = { path = "../neo-api-rs", version = "0.1.0" }
once_cell = "1"
